add_shopping_list_item:
  name: Add Shopping List Item
  description: Adds a shopping list item to the shopping list
  fields:
    item:
      name: Item
      description: The item to add
      required: true
      example: Milk

remove_shopping_list_item:
  name: Remove Shopping List Item
  description: Removes a shopping list item from the shopping list
  fields:
    item:
      name: Item
      description: The item to remove
      required: true
      example: Milk